apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/sales/
patchesStrategicMerge:
- ./dev-sales-patch.yaml
images:
- name: sales-api-image # name from the image in base-sales.yaml
  newName: sales-api # magically changes name
  newTag: "1.0"
