apiVersion: v1
kind: Namespace
metadata:
  name: sales-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales # name of the pod
  namespace: sales-system
spec:
  selector:
    matchLabels:
      app: sales
  template:
    metadata:
      labels:
        app: sales # allows us to query with kubectl the pod named sales
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: sales-api
        image: sales-api-image